### ISSUE TITLE
val set

### ISSUE THREAD

**Issue by maxwellgodv** [octree-nn/octformer#10]
您好，我看到您说在test集合的结果是同时使用train和val的数据集进行训练，那请问训练的时候验证集应该怎么设置呢，十分感谢

**Comment by wang-ps** [comment]
不需要验证集，或者保留少量的验证集数据用于监测训练过程。
这个阶段不用再调参了，利用之前确定了的训练参数。

**Comment by maxwellgodv** [comment]
您好，十分感谢，但是我还是有些问题，请问是在之前预训练好的基础上开始训练一些轮次，还是利用train和val从头开始训练呢，十分感谢您的回答。

**Comment by wang-ps** [comment]
从头训练，你说的第一个策略也是可以的

**Comment by maxwellgodv** [comment]
谢谢您，十分感谢，那这样的话怎么判定哪一轮的模型结果最好，用来输出test的结果呢
