### ISSUE TITLE
Exclude Normals from Training

### ISSUE THREAD

**Issue by MoritzLennartz** [octree-nn/octformer#11]
Hello, 

thank you for your nice work! I am using your Model for a Training with my own Dataset. But i dont have any Informationen in my dataset about the normals. 

How can i exclude the normals in the training. 

When i set `read_file = ReadFile(has_normal=False, has_color=True, has_label=True)` in scannet.py line 222 to `False` i receive a key Error saying `KeyError: 'normals'`

Thank your for your help 

Best
Moritz

**Comment by wang-ps** [comment]
I suspect that the error `Key Error: 'normals'` comes from the following line of code.  You should modify source codes that use normals accordingly, if the normals are not read from data. 

https://github.com/octree-nn/octformer/blob/41957017fb04977dcca4b6b2fa5a936b0781c0b6/datasets/scannet.py#L148
