### ISSUE TITLE
Visualization of ScanNet

### ISSUE THREAD

**Issue by TainanKyle** [octree-nn/octformer#12]
Hi. Thank you for your work.
Is it possible to run one scan of ScanNet with pretrained weight, and generate a visualization result like Fig. 5 in your paper?

**Comment by wang-ps** [comment]
Yes.
You can run one scan of ScanNet with pretrained weight, and the network will produce the predicted labels for each point. 
Then you can visualize the labels with any color coding you like with meshlab or blender.  The results in Fig. 5 involve global illumination rendered with the blender.
