### ISSUE TITLE
tools/seg_scannet200.py

### ISSUE THREAD

**Issue by weiguangzhao** [octree-nn/octformer#13]
Hi，thanks  for your great work. When I run the command:
`python tools/seg_scannet200.py --run process_scannet --path_in <scannet_folder>  \
       --path_out data/scanet200.npz  --align_axis  --scannet200`
It seems that there is no seg_scannet200.py file. I guess it  should be " tools/seg_scannet.py " in the command.

**Comment by wang-ps** [comment]
Thank you so much for pointing out this issue. I have fixed it.
