### ISSUE TITLE
dwconv

### ISSUE THREAD

**Issue by lvhyang** [octree-nn/octformer#16]
您好，我在进行dwconv库的操作时，好像出现了维度不匹配的问题。
<img width="573" alt="微信图片_20240326181542" src="https://github.com/octree-nn/octformer/assets/71586425/61cb2642-2b99-4a81-8a71-818a95e897e4">
这是我的报错信息，谢谢

**Comment by wang-ps** [comment]
请你严格按照readme编译代码，
我机器上可以运行，不能复现你的问题

**Comment by duanzantingxie** [comment]
Dear wang-ps,

Hello! I'm a researcher interested in point cloud segmentation tasks. I'm particularly intrigued by your open-source project OctFormer and its performance in point cloud classification tasks. I'm eager to learn more about OctFormer's performance metrics and experimental results in this area. Are there any relevant literature or experimental data you could share? I'm looking forward to your response. Thank you!

Best regards,
Liu-yt

**Comment by lvhyang** [comment]
是的，我修复了这个问题，在我重新安装dwconv库之后
