### ISSUE TITLE
Point Classification

### ISSUE THREAD

**Issue by duanzantingxie** [octree-nn/octformer#17]
Dear wang-ps,

Hello! I'm a researcher interested in point cloud segmentation tasks. I'm particularly intrigued by your open-source project OctFormer and its performance in point cloud classification tasks. I'm eager to learn more about OctFormer's performance metrics and experimental results in this area. Are there any relevant literature or experimental data you could share? I'm looking forward to your response. Thank you!

Best regards,
Liu-yt

**Comment by wang-ps** [comment]
I did an experiment on point cloud classification with OctFormer. The reference is as follows. 
https://github.com/octree-nn/octformer?tab=readme-ov-file#5-modelnet40-classification

OctFormer achieved an accuracy of 92.7% on ModelNet40, which is a decent result, although it is not the best.  I am confident about the capability of OctFormer. However, it is tricky to achieve better accuracy on ModelNet40 for OctFormer.  It is known that transformers are data-hungry. However, the training set of ModelNet40 contains only about 9k point clouds, which makes the parameter tuning cumbersome; and I have other important things to do.

**Comment by duanzantingxie** [comment]
Dear wang-ps,

I wanted to express my sincere gratitude for your prompt response and for your valuable contributions to the field of point cloud representation learning. Your insights and efforts are greatly appreciated. I truly appreciate the time you took to address my inquiry about OctFormer's performance in point cloud classification tasks.

Wishing you continued success in all your endeavors.

Best regards,
Liu-yt
