### ISSUE TITLE
test

### ISSUE THREAD

**Issue by fyj534609** [octree-nn/octformer#18]
您好，我想在scannet的test上测试后将得到的结果提交给scannet官网，我看到似乎是需要在所有的scannet数据（包括train和val）上训练后，再在test上进行预测，那请问在产生的所有10-600model.pth，怎么样选择bestmodel进行预测，或者有一些什么其他需要注意的地方，十分期待您的回答。

**Comment by wang-ps** [comment]
我选的是最后一个，因为这次test label是未知的，训练的超参数也已经用val集确定了，不需要再调了。另外，可以多训练几次，进行模型ensembles。

**Comment by fyj534609** [comment]
模型ensembles

> 我选的是最后一个，因为这次test label是未知的，训练的超参数也已经用val集确定了，不需要再调了。另外，可以多训练几次，进行模型ensembles。

您好，模型ensembles指的具体是，我不太清楚，您能稍微解释一下吗

**Comment by wang-ps** [comment]
多训练几次，选择最后一个model。多次执行后，把预测概率平均一下，得到最后的label

**Comment by fyj534609** [comment]
> 多训练几次，选择最后一个model。多次执行后，把预测概率平均一下，得到最后的label

您是指多预测几次然后voting嘛，我如果需要在test上预测提交给scannet的话，需要先在所有数据集（train和val）上训练一个模型，然后使用voting预测出结果然后提交给scannet这样嘛。我发现代码中有test接口但是没有使用，直接使用scripts/run_seg_scannet.py下的test接口就可以完成上述操作嘛
