### ISSUE TITLE
ScanNet Segmentation

### ISSUE THREAD

**Issue by fyj534609** [octree-nn/octformer#2]
Hello, I would like to ask whether when downloading the ScanNet Segmentation dataset, do I need to download the complete dataset of 1.3TB, or is it possible to download only a part of it?

**Comment by wang-ps** [comment]
I downloaded the whole dataset the first time I tried to process ScanNet. 
The dataset after processing is small  and is only about 15G.

**Comment by fyj534609** [comment]
Thank you for your response. So should I download the whole 1.3TB dataset and then use the command 'python tools/seg_scannet.py --run process_scannet --path_in <scannet_folder>' to process the downloaded dataset, resulting in about 15GB of remaining data?

**Comment by wang-ps** [comment]
Maybe, you can choose not to download the RGBD scan frames.  An example is shown below. The following is all you need to generate the required dataset

![image](https://github.com/octree-nn/octformer/assets/7525130/47ba8d31-5b61-47b9-9a5d-06983c27c095)

**Comment by fyj534609** [comment]
Thank you for your response. Could you please confirm if the final downloaded file directory should look like this?
├── scannet
│   ├── scans
│   │   ├── [scene_id]
│   │   │   ├── [scene_id].aggregation.json
│   │   │   ├── [scene_id].txt
│   │   │   ├── [scene_id]_vh_clean.aggregation.json
│   │   │   ├── [scene_id]_vh_clean.segs.json
│   │   │   ├── [scene_id]_vh_clean_2.0.010000.segs.json
│   │   │   ├── [scene_id]_vh_clean_2.labels.ply
│   │   │   ├── [scene_id]_vh_clean_2.ply
│   ├── scans_test
│   │   ├── [scene_id]
│   │   │   ├── [scene_id].aggregation.json
│   │   │   ├── [scene_id].txt
│   │   │   ├── [scene_id]_vh_clean.aggregation.json
│   │   │   ├── [scene_id]_vh_clean.segs.json
│   │   │   ├── [scene_id]_vh_clean_2.0.010000.segs.json
│   │   │   ├── [scene_id]_vh_clean_2.ply
│   ├── scannetv2-labels.combined.tsv
![1691115392320](https://github.com/octree-nn/octformer/assets/118888481/6a0004bb-4c94-46e2-ab57-4e06261f8a02)

**Comment by fyj534609** [comment]
> Maybe, you can choose not to download the RGBD scan frames. An example is shown below. The following is all you need to generate the required dataset
> 
> ![image](https://user-images.githubusercontent.com/7525130/258272721-47ba8d31-5b61-47b9-9a5d-06983c27c095.png)

Thank you for your response. Could you please confirm if the final downloaded file directory should look like this?
├── scannet
│   ├── scans
│   │   ├── [scene_id]
│   │   │   ├── [scene_id].aggregation.json
│   │   │   ├── [scene_id].txt
│   │   │   ├── [scene_id]_vh_clean.aggregation.json
│   │   │   ├── [scene_id]_vh_clean.segs.json
│   │   │   ├── [scene_id]_vh_clean_2.0.010000.segs.json
│   │   │   ├── [scene_id]_vh_clean_2.labels.ply
│   │   │   ├── [scene_id]_vh_clean_2.ply
│   ├── scans_test
│   │   ├── [scene_id]
│   │   │   ├── [scene_id].aggregation.json
│   │   │   ├── [scene_id].txt
│   │   │   ├── [scene_id]_vh_clean.aggregation.json
│   │   │   ├── [scene_id]_vh_clean.segs.json
│   │   │   ├── [scene_id]_vh_clean_2.0.010000.segs.json
│   │   │   ├── [scene_id]_vh_clean_2.ply
│   ├── scannetv2-labels.combined.tsv
![1691115392320](https://github.com/octree-nn/octformer/assets/118888481/6127e84f-2b5b-4de0-a5b8-d6a40c5dfd11)

**Comment by wang-ps** [comment]
Yes, very informative and clear figure!

**Comment by wang-ps** [comment]
> I downloaded the whole dataset the first time I tried to process ScanNet. The dataset after processing is small and is only about 15G.

Correct:  the dataset after process is about 8G

**Comment by fyj534609** [comment]
> Yes, very informative and clear figure!

Thank you very much for your reply!
