### ISSUE TITLE
conv_error

### ISSUE THREAD

**Issue by lvhyang** [octree-nn/octformer#22]
![image](https://github.com/octree-nn/octformer/assets/71586425/b0913bd0-825d-4dbf-a26e-84dc0687275f)
您好，我在使用octree提取特征时，发生了如上错误。具体是在执行Patchembed的八叉树卷积时出现了shape_error。
请问我该如何解决，谢谢。

**Comment by lvhyang** [comment]
![image](https://github.com/octree-nn/octformer/assets/71586425/625ad3da-22f9-4f30-93bf-71c8bc7fe096)
这是我的具体报错信息

**Comment by wang-ps** [comment]
是运行我的代码的错误吗？还是你自己写的代码？

**Comment by lvhyang** [comment]
![image](https://github.com/octree-nn/octformer/assets/71586425/6b07ecfd-7b20-4596-9169-ebde43e54187)
是我用自己的数据集作为输入运行您的代码，具体错误的一行我打了断点。

**Comment by lvhyang** [comment]
我发现了错误的原因，point在build_octree时在第二层就不再增长了，导致八叉树的结点数为[1，8，8，8，8，8，8，8，8，8，8]，我将继续寻找这个错误的原因。
