### ISSUE TITLE
About sub-figures (d) and (g) of Fig3

### ISSUE THREAD

**Issue by sz3623** [octree-nn/octformer#26]
Hello, the sorting rule I got based on the dilation setting in Algorithm 1 is inconsistent with d and g in Figure 3. 
Does sorting with the dilation setting operate on one dimension, or two?

**Comment by sz3623** [comment]
![Snipaste_2024-05-30_18-43-46](https://github.com/octree-nn/octformer/assets/48540066/39c79baa-deda-4a8d-8387-5fb780b8e6e7)

**Comment by wang-ps** [comment]
> Does sorting with the dilation setting operate on one dimension, or two?

The sorting operation happens when building octrees, in one dimension. And I do not understand why Algorithm 1 is inconsistent with d and g in Figure 3.

**Comment by sz3623** [comment]
I drew the above Figure (number=7, dilation=2) for this process, if I understand it correctly. Therefore, the setting of dilation is to interchange the positions of the points in a one-dimensional order. So, are the positions of "2" and "9" swapped? If so, dilation operates on the entire group (number=7), 9 = 2 + 7 * (2-1). What does the dilation setting mean?
