### ISSUE TITLE
About the use of OctrideMaxPool and OctrideMaxUnpool

### ISSUE THREAD

**Issue by Dreamxxxxxx** [octree-nn/octformer#27]
Hello, thank you very much for the author's excellent work. I am very interested in it,
When using octree_max_unpool, passing depth+1 in this part of the code will result in a mask exceeding the index of the data when entering octreed_depad, which is an error message.
![image](https://github.com/octree-nn/octformer/assets/45550199/29ca8293-e4ad-472c-a2b6-33ef59177ac6)
![1](https://github.com/octree-nn/octformer/assets/45550199/75afda62-7862-4fac-b15b-ff519fbc2e7a)
I will print the shape in octree_depad as shown in the picture.
![image (2)](https://github.com/octree-nn/octformer/assets/45550199/1f45bd92-a9bf-4c52-bbbf-f0846f3deac2)
![3](https://github.com/octree-nn/octformer/assets/45550199/b4ac3f25-db75-4659-a592-1d81f72a327b)
If I only pass in depth without+1, then there is no such issue, but I am not sure if this is correct?
![image (4)](https://github.com/octree-nn/octformer/assets/45550199/1f0fc8d4-cd97-4a70-a4c1-01478848987d)
The following is the code I used in the code for using OctreeMaxPool and OctreeMaxUnpool
![image (5)](https://github.com/octree-nn/octformer/assets/45550199/8a2ed198-a5b3-4fa6-80da-265246281d8e)
![image (6)](https://github.com/octree-nn/octformer/assets/45550199/4235f380-e2fb-4431-b2b8-08131415c639)

**Comment by wang-ps** [comment]
Thank you so much for figuring out this issue @Dreamxxxxxx ! I will check it soon.

**Comment by wang-ps** [comment]
@Dreamxxxxxx  I checked the code just now. I think the code is OK. Its usage can be found here (https://github.com/octree-nn/ocnn-pytorch/blob/master/test/test_octree_pool.py#L33) and here (https://github.com/octree-nn/ocnn-pytorch/blob/master/ocnn/models/segnet.py#L65)
