### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by windboy6** [octree-nn/octformer#28]
Hello,
I would like to know how to visualize sparse voxels, do you have any suggestions? Thanks.

**Comment by wang-ps** [comment]
One possible solution is to get the coordinates of octree nodes in each octree depth, with which each octree can be drawn as a 3D cube.  The following function can be used to get the coordinates.
https://ocnn-pytorch.readthedocs.io/en/latest/modules/octree.html#ocnn.octree.Octree.xyzb
