### ISSUE TITLE
Request to add instructions to work with a new dataset

### ISSUE THREAD

**Issue by AntiLibrary5** [octree-nn/octformer#29]
Hi,
I ran into this work recently and really liked the writing and visuals. Great to see the reproducibility stamp too on the codebase. 
We've been trying to use OctFormer on a dataset for 3d medical segmentation. So far I am trying to scratch my way around to have the dataset as close to scannet which could work. But, it would be great to the community if generic instructions were added to be able to work with new datasets. Kindly take it under consideration.

Thanks,
Best.

**Comment by wang-ps** [comment]
Thanks for your great suggestion!  I will try to add instructions in the future.

And your solution of following the scannet dataset is practical and smart.
