### ISSUE TITLE
mIoU

### ISSUE THREAD

**Issue by fyj534609** [octree-nn/octformer#3]
Hello, may I inquire if the mIoU metric mentioned in the paper refers to the test/mIoU generated during training or the test/mIoU_part?

**Comment by wang-ps** [comment]
It is the `test/mIoU_part` in the paper.
The  `test/mIoU` is used for ShapeNet Segmentation. 

The relevant implementions can be found in the follows two places:

https://github.com/octree-nn/octformer/blob/master/segmentation.py#L135
https://github.com/octree-nn/octformer/blob/master/tools/seg_scannet.py#L270

**Comment by fyj534609** [comment]
Thank you very much
