### ISSUE TITLE
AssertionError: The shape of input data is wrong in OctFormerCls model

### ISSUE THREAD

**Issue by FlorianDAVAUX** [octree-nn/octformer#30]
I am encountering an issue when trying to use the OctFormerCls model.
I forked your repository and added a test notebook. In this notebook I am trying to use your OctFormerCls model with one of your data (airplane001.off).

## Parameters Used
- channel : 4
- octree depth : 6
- feature : ND

I built a fake batch with this data, a random label and this octree.

## Error
When I run the script I have this error :
```bash
AssertionError: The shape of input data is wrong.
```

## Notebook Permalink
```bash
https://github.com/FlorianDAVAUX/octformer/blob/b41c63f412148bcfb64a724b1144574d8944c058/test.ipynb
```

**Comment by wang-ps** [comment]
Thanks for your interest in OctFormer. Please refer to the instructions here (https://github.com/octree-nn/octformer?tab=readme-ov-file#5-modelnet40-classification) to run the classification experiments.

**Comment by FlorianDAVAUX** [comment]
Thanks for your response. I already followed the instructions you give here (https://github.com/octree-nn/octformer?tab=readme-ov-file#5-modelnet40-classification). The fact is, I wanted to understand your model and try my own experiment by using your OctformerCLS model. The fact is, I have an issue with input shape data and I do not understand why because I use the same parameters than you.

Do you have any idea of what could it be?

It seems that the

**Comment by FlorianDAVAUX** [comment]
Thanks for your response. I already followed the instructions you give here (https://github.com/octree-nn/octformer?tab=readme-ov-file#5-modelnet40-classification).
The fact is, I want to understand your model and try my own experiment by using your OctformerCLS model. However, I have an issue with input shape data and I do not understand why because I use the same parameters as you.

Do you have any idea of what could it be?

It seems that the error occurs when **OctformerCLS** calls **Octformer** and then, in the class **PatchEmbed**.

**Comment by wang-ps** [comment]
Please take a look at the code I provided to understand the code. I am so sorry that I might have no bandwidth to debug the code out of my repository.
