### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Dreamxxxxxx** [octree-nn/octformer#32]
Thank you very much for your excellent work，but I encountered an assertions error while running python scripts/run_seg_scannet.py --gpu 0,1 --alias scannet --port 10001.I don't know where the problem lies, I hope you can give me some guidance. Thank you very much！
![image](https://github.com/user-attachments/assets/12f0c1ed-7918-43cf-a74c-6e5e3df8d859)

**Comment by wang-ps** [comment]
`pip install -U ocnn==2.2.1` can fix it.
