### ISSUE TITLE
how to train s3dis

### ISSUE THREAD

**Issue by MNEXT11** [octree-nn/octformer#33]
Can this network be trained on the s3dis dataset and what pre-processing steps are required

**Comment by wang-ps** [comment]
Yes, it is possible to use OctFormer for s3dis.
Please refer to the ScanNet experiment to prepare the data accordingly.

**Comment by MNEXT11** [comment]
> Yes, it is possible to use OctFormer for s3dis. Please refer to the ScanNet experiment to prepare the data accordingly.

Can I use pointnet preprocessed s3dis training?

**Comment by MNEXT11** [comment]
> Yes, it is possible to use OctFormer for s3dis. Please refer to the ScanNet experiment to prepare the data accordingly.

Can I use pointnet preprocessed s3dis training?
