### ISSUE TITLE
How to use the trained classification model for prediction

### ISSUE THREAD

**Issue by narges-tk** [octree-nn/octformer#35]
Hi! Thanks for sharing your work! I wonder how can I use the trained classification model for prediction. I found no comment for that. Any guidance would be appreciated. Thanks!

**Comment by wang-ps** [comment]
You can use the following command to use the trained classification model:
```
python classification.py --config configs/cls_m40.yaml  \
            SOLVER.gpu 0,  \
            SOLVER.run evaluate   \
            SOLVER.ckpt <the path to the trained model>
```
