### ISSUE TITLE
voxel size

### ISSUE THREAD

**Issue by maxwellgodv** [octree-nn/octformer#4]
您好，我看到您的论文中说在voxel size为1cm的时候模型有较好表现，请问代码中那里可以调整voxel size为1cm呢

**Comment by wang-ps** [comment]
目前代码里scannet的实验，voxel size 是1cm的。

输入的点云，先被下面缩放因子10.24缩放到 [-1, 1]之间，然后构建深度为11的八叉树，等价于分辨率为2048。通过缩放因子和八叉树两个因素，使得一个最细分辨率的八叉树格子的大小为1cm。
https://github.com/octree-nn/octformer/blob/d727ba08fb801c7340784440ef5e49ec4c53218a/datasets/scannet.py#L126

**Comment by maxwellgodv** [comment]
好的，谢谢您的回答，我在杭州听了您的演讲，并在两张3090上尝试跑了目前代码里scannet的实验但是在test上的miou只能达到74.7，请问这是显卡的问题还是其他的设置没有设置好

**Comment by wang-ps** [comment]
你说的是测试集还是验证集？以及是否进行了voting？我公布了validation的训练曲线，没有voting的情况下74.7是正常的结果。
请看readme的说明。另外尽量在所有的配置都和我们一样，如果两个gpu，可能训练参数需要微调。

![image](https://github.com/octree-nn/octformer/assets/7525130/9c8c5052-4a34-473c-a3fe-e8a70054e2e6)

**Comment by maxwellgodv** [comment]
十分感谢您的回答，这是训练的时候产生的log，是在没有voting的情况下，那么怎么开启voting呢，我没有能找到接口，十分感谢
<img width="253" alt="a74a481740411336e1b0a12655bd5bf" src="https://github.com/octree-nn/octformer/assets/127387074/6c5fa344-ac66-45a1-a022-e6ef6f5614b8">

**Comment by wang-ps** [comment]
那是正常的。这个是validation数据集上的mIoU，我release出来的训练曲线是74.8，是正常的。
执行上面的readme的截图的**第三步**就可以了实现voting了，会再涨一些性能。

**Comment by maxwellgodv** [comment]
好的十分感谢您，这个是validation数据集上的mIoU，那执行上面的readme的第三步是实现voting了后的mIoU是论文中val一栏中voting后的75.7吗，那76.6是在哪得出的，我没有找到相关数据，十分感谢您的回答，谢谢您
<img width="427" alt="ef0c77bf41b76925dc00884dcbf155d" src="https://github.com/octree-nn/octformer/assets/127387074/59b0cba9-7dfa-44a9-92af-e35acb3d444d">

**Comment by wang-ps** [comment]
神经网络的结果是有一定波动性的。voting的数据就是validation数据集的数据。
现在的release出来的权重voting 之后得到的76.6，对应于这里的75.7。
再训练一次，有可能结果会稍有变化，可能在75.7附近稍有波动。

**Comment by maxwellgodv** [comment]
> 神经网络的结果是有一定波动性的。voting的数据就是validation数据集的数据。 现在的release出来的权重voting 之后得到的76.6，对应于这里的75.7。 再训练一次，有可能结果会稍有变化，可能在75.7附近稍有波动。

您好，十分感谢，我没有十分理解您的意思，使用这行命令得出的IoU，应该对应于上个图中的75.7吗，还是对应于76.6，十分感谢您的耐心解答
<img width="492" alt="1695288625237" src="https://github.com/octree-nn/octformer/assets/127387074/905939cc-347d-484d-97d1-4f3a44a1c61c">

**Comment by wang-ps** [comment]
使用这个命令得到的是76.6，比论文中高一点点。
论文中的75.7也是通过这个命令得到的。
每训练一次，结果都会稍有波动，1个点以内波动都是正常的。

**Comment by maxwellgodv** [comment]
好的，谢谢您的耐心回答，那下面表格中的76.6和75.7均为“python scripts/run_seg_scannet.py --gpu 0 --alias scannet --run validate”这行命令得出，那val和test的区分是在哪里呢，十分感激您。
![image](https://github.com/octree-nn/octformer/assets/127387074/0c782198-f7b4-497e-83b0-e9d5ae83520f)

**Comment by maxwellgodv** [comment]
> 使用这个命令得到的是76.6，比论文中高一点点。 论文中的75.7也是通过这个命令得到的。 每训练一次，结果都会稍有波动，1个点以内波动都是正常的。

您好，可能是我没有说清楚我的问题，“python scripts/run_seg_scannet.py --gpu 0 --alias scannet --run validate”得到是论文中val一栏下的75.7，那在论文中test下的 76.6应该怎么得出呢，十分感激！
![image](https://github.com/octree-nn/octformer/assets/127387074/ae2cc9b5-204d-4f9f-9dad-e076118bd02f)

**Comment by wang-ps** [comment]
测试集的结果需要在scannet的测试集数据上运行，，然后提交到scannet的官网上，由他们计算出mIoU，测试集上的label是不公开的。具体的介绍需要参考scannet的官网的操作步骤。
