### ISSUE TITLE
Check failed: error == cudaSuccess  invalid configuration argument

### ISSUE THREAD

**Issue by boqiuphd** [octree-nn/octformer#6]
Thank you for your great work, I have successfully trained and tested on the Scannet dataset using octformer, but an error occurs when training on my own dataset, and despite looking up various sources, I can't determine the cause of the error, so I'd like to ask you which part of the code this might be a problem with?

############################################################
Logdir: logs/railway3d/octformer_railway3d
-  Epoch: 1, train/loss: 2.418, train/accu: 0.083, iter: 0                      
-> Epoch: 1, train/loss: 2.408, train/accu: 0.098, time/data: 72.928, time/batc 
   h: 79.334, time: 2023/06/22 23:17:55, duration: 555.40s                      
-  Epoch: 2, train/loss: 2.414, train/accu: 0.085, iter: 0                      
-> Epoch: 2, train/loss: 2.397, train/accu: 0.105, time/data: 42.071, time/batc 
   h: 44.832, time: 2023/06/22 23:23:09, duration: 313.83s                      
-  Epoch: 3, train/loss: 2.361, train/accu: 0.117, iter: 0                      
-> Epoch: 3, train/loss: 2.354, train/accu: 0.157, time/data: 52.162, time/batc 
   h: 54.882, time: 2023/06/22 23:29:33, duration: 384.17s                      
-  Epoch: 4, train/loss: 2.388, train/accu: 0.145, iter: 0                      
-> Epoch: 4, train/loss: 2.285, train/accu: 0.277, time/data: 57.457, time/batc 
   h: 60.386, time: 2023/06/22 23:36:36, duration: 422.70s                      
-  Epoch: 5, train/loss: 2.284, train/accu: 0.468, iter: 0                      
-> Epoch: 5, train/loss: 2.105, train/accu: 0.534, time/data: 55.314, time/batc 
   h: 58.113, time: 2023/06/22 23:43:22, duration: 406.79s                      
  1%|▎                                      | 4/600 [34:42<67:42:25, 408.97s/it]
[F dwconv.cu:111] Check failed: error == cudaSuccess  invalid configuration argument
Aborted (core dumped)                            | 1/12 [00:00<00:10,  1.03it/s]

############################################################

**Runtime error: cuda error: invalid configuration argument**

The information I've found suggests that this error is usually caused by using an invalid CUDA configuration argument. There are several common troubleshooting options:

1. Make sure the CUDA environment is correct: Check if the CUDA installation is correct and compatible with the code version. If the CUDA version does not match, then it is likely that an invalid configuration parameter error will occur.

2. Check CUDA thread block, thread and shared memory size settings: If the program uses CUDA kernel functions, you need to check whether the CUDA thread block, thread and shared memory size settings are correct. Make sure that the size set does not exceed the maximum limit of the GPU device, otherwise invalid configuration parameter errors will occur.

3. Check CUDA device number and ID settings: If the program uses multiple CUDA devices, you need to check if the device number and ID settings are correct. Make sure that the program is executed on the correct GPU device, otherwise invalid configuration parameter errors will occur.

4. Check CUDA memory usage: If the program uses a lot of GPU memory resources, you need to check if the memory usage is correct. Invalid configuration parameter errors may also result if memory is not used correctly.

I would like to know which part of the code in octformer can be checked for these cases?
Looking forward to getting your response!

**Comment by wang-ps** [comment]
I am so sorry that I could not provide more advice  since I have not encountered this issue before.

**Comment by peter218** [comment]
I also meet the same problem，I don't know how to solve the issue
