### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by 150de** [octree-nn/octformer#7]
Hello sir，do we need to download the full dataset（1.3T）or other  smaller dataset to train？

**Comment by 150de** [comment]
I'm talking about the Scannet dataset

**Comment by wang-ps** [comment]
The following is a screen shot from the official repository of ScanNet (https://github.com/ScanNet/ScanNet). The highlighted files are not needed for training and can be omitted when downloading the dataset.

![image](https://github.com/octree-nn/octformer/assets/7525130/b033eb1b-9936-4816-a553-0b590cefdc42)

**Comment by 150de** [comment]
Thank you very much for your reply!Have a nice day.
