### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by 150de** [octree-nn/octformer#8]
Hello sir, how can I visualize the trained point cloud model like Figure 1 in your paper? I did not conduct a complete training (due to insufficient GPU memory), but conducted a complete evaluation.Looking forward to your reply.

**Comment by wang-ps** [comment]
The figure is rendered with Blender by assigning one color to the points belonging to one patch. 

By the way, Figure 1 is for illustrating the patch partition, not the predicting results.
