### ISSUE TITLE
test

### ISSUE THREAD

**Issue by fyj534609** [octree-nn/octformer#9]
您好，我想问一下关于test的数据是需要test之后提交到官网得到最终的miou，但是怎么得到test出来的结果呢，似乎没有找到相关命令，谢谢您

**Comment by wang-ps** [comment]
做法类似于evaluation set。
只需要把原来的evaluation set的数据替换成test set即可。
需要说明的是，我按照之前论文的做法，为了得到test集合的结果，我重新用所有的数据（包括training set 和evaluation set）进行了训练。

**Comment by fyj534609** [comment]
> 做法类似于evaluation set。 只需要把原来的evaluation set的数据替换成test set即可。 需要说明的是，我按照之前论文的做法，为了得到test集合的结果，我重新用所有的数据（包括training set 和evaluation set）进行了训练。

十分感谢您的回答，我想请问一下在您使用所有数据（包括training 和evaluation ）训练的时候，仍旧用evaluation的数据每十轮验证然后保存在evaluation中miou最好的模型嘛
